version: '3'
services:
  mongodb:
    image: "mongo:latest"
    restart: always
    volumes:
      - "bustimes_mongodb:/data/db"
      - "./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh"
    env_file:
      - env_file
    networks:
      - mongodb_nw
  db:
    image: "postgres:12"
    volumes:
      - "busttimes_database:/var/lib/postgresql/data"
    env_file:
      - env_file
    networks:
      - db_nw
  flaskapp:
    build: .
    env_file:
      - env_file
    ports:
      - "8080:5000"
    volumes:
      - .:/home/flaskapp
      - ./migrations:/home/flaskapp/migrations
    networks:
      - db_nw
      - mongodb_nw
    depends_on:
      - db
  client:
    build: ./client
    ports: 
      - "3000:3000"
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/public:/usr/src/app/public
    depends_on:
      - flaskapp
networks:
  db_nw:
    driver: bridge
  mongodb_nw:
    driver: bridge
volumes:
  busttimes_database:
  bustimes_mongodb: