"""add station_name and naptan_id to requests table

Revision ID: 17372e4bde0b
Revises: 6134b695b1b9
Create Date: 2019-11-03 14:14:19.389566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17372e4bde0b'
down_revision = '6134b695b1b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('naptan_id', sa.String(), nullable=False))
    op.add_column('requests', sa.Column('station_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'station_name')
    op.drop_column('requests', 'naptan_id')
    # ### end Alembic commands ###
